services:
  worker: &worker
    build:
      context: ../
      dockerfile: ./development/Dockerfile
      args:
        NETBOX_VERSION: ${NETBOX_VERSION}
    command: sh -c "python manage.py rqworker"
    depends_on:
      - postgres
      - redis
    env_file: .env
    environment:
      - POSTGRES_HOST=postgres
      - REDIS_CACHE_HOST=redis
      - REDIS_HOST=redis
    volumes:
      - custom_scripts:/opt/netbox/netbox/scripts
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../validity:/plugin/validity/validity
      - git_repos:/opt/git_repos/
    networks:
      - netboxnet

  netbox:
    <<: *worker
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
      - "5678:5678"
    depends_on:
      - postgres
      - worker
      - redis

  postgres:
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - netboxnet

  redis:
    image: redis:7-alpine
    command: --appendonly yes --requirepass $REDIS_PASSWORD
    env_file: .env
    networks:
      - netboxnet

volumes:
  pgdata:
  git_repos:
  custom_scripts:

networks:
  netboxnet:
