site_name: Validity
repo_url: https://github.com/amyasnikov/validity/
theme: readthedocs
nav:
    - Intro: index.md
    - Installation: installation.md
    - Quickstart: quickstart.md
markdown_extensions:
  - admonition
  - tables
plugins:
  - include-markdown
