site_name: Validity
repo_url: https://github.com/amyasnikov/validity/
theme:
  name: material
  features:
    - search.suggest
  icon:
    logo: material/checkbox-marked-circle-outline
nav:
  - Intro: index.md
  - Installation:
    - Installation: installation/installation.md
    - Plugin Settings: installation/plugin_settings.md
    - NetBox Compatibility: installation/netbox_compatibility.md
    - Upgrading: installation/upgrading.md
  - Quickstart: quickstart.md
  - 'Quickstart: Polling': quickstart_polling.md
  - Entities:
    - Data Sources: entities/datasources.md
    - Selectors: entities/selectors.md
    - Serializers: entities/serializers.md
    - Compliance Tests: entities/tests.md
    - Name Sets: entities/namesets.md
    - Results & Reports: entities/results_and_reports.md
    - Pollers: entities/pollers.md
    - Commands: entities/commands.md
    - Backup Points: entities/backuppoints.md
    - Scripts: entities/scripts.md
  - Features & Tips:
    - How to write the Tests: features/howto_write_tests.md
    - How to work with Device State: features/state.md
    - Dynamic Pairs: features/dynamic_pairs.md
    - Webhooks: features/webhooks.md
    - Custom Pollers: features/custom_pollers.md
    - Config Backup: features/config_backup.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables
  - toc
plugins:
  - include-markdown
  - search

extra_css:
  - extra_styles.css
