name: Build NetBox
inputs:
  netbox_version:
    required: true

runs:
  using: "composite"
  steps:
  - name: Define .env
    run: >-
      cp development/.env.example development/.env
      && sed -i "s/NETBOX_VERSION=develop/NETBOX_VERSION=${{ inputs.netbox_version }}/" development/.env

  - name: docker version
    run: docker version && docker compose version

  - name: Build netbox
    run: cd development && docker compose build
