# Generated by Django 4.1.5 on 2023-02-19 13:24

from django.db import migrations, models
import taggit.managers
import utilities.json


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0084_staging"),
        ("validity", "0002_custom_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="compliancetestresult",
            options={"ordering": ("-created",)},
        ),
        migrations.AddField(
            model_name="compliancetest",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="NameSet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ("created", models.DateTimeField(auto_now_add=True, null=True)),
                ("last_updated", models.DateTimeField(auto_now=True, null=True)),
                (
                    "custom_field_data",
                    models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField()),
                ("_global", models.BooleanField(blank=True, default=False)),
                ("definitions", models.TextField()),
                ("serializers", models.ManyToManyField(blank=True, to="validity.configserializer")),
                ("tags", taggit.managers.TaggableManager(through="extras.TaggedItem", to="extras.Tag")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
