# Generated by Django 4.1.8 on 2023-05-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0002_custom_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="complianceselector",
            name="dp_tag_prefix",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
