# Generated by Django 4.1.5 on 2023-02-25 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0004_alter_complianceselector_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compliancetestresult",
            name="explanation",
            field=models.JSONField(default=list),
        ),
    ]
