# Generated by Django 4.1.5 on 2023-02-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0005_alter_compliancetestresult_explanation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compliancetestresult",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="nameset",
            name="serializers",
        ),
        migrations.AddField(
            model_name="nameset",
            name="tests",
            field=models.ManyToManyField(blank=True, related_name="namesets", to="validity.compliancetest"),
        ),
    ]
