# Generated by Django 4.1.5 on 2023-03-03 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0006_remove_compliancetestresult_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancetest",
            name="severity",
            field=models.CharField(default="MIDDLE", max_length=10),
        ),
    ]
