# Generated by Django 4.1.5 on 2023-03-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0007_compliancetest_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="configserializer",
            name="extraction_method",
            field=models.CharField(default="TTP", max_length=10),
        ),
        migrations.AlterField(
            model_name="configserializer",
            name="ttp_template",
            field=models.TextField(blank=True),
        ),
    ]
