# Generated by Django 4.2.9 on 2024-02-19 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0008_script_change"),
    ]

    operations = [
        migrations.AddField(
            model_name="serializer",
            name="parameters",
            field=models.JSONField(default=dict, blank=True),
        ),
    ]
