# Generated by Django 4.1.5 on 2023-03-04 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("validity", "0008_configserializer_extraction_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compliancetest",
            name="file_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="compliancetest",
            name="repo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="validity.gitrepo"
            ),
        ),
        migrations.AddField(
            model_name="configserializer",
            name="file_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="configserializer",
            name="repo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="validity.gitrepo"
            ),
        ),
        migrations.AddField(
            model_name="nameset",
            name="file_path",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="nameset",
            name="repo",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="validity.gitrepo"
            ),
        ),
    ]
