# Generated by Django 5.2.1 on 2025-05-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validity', '0012_backuppoint_devicerole'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancetest',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
