# Generated by Django 6.1 on 2026-09-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validity', '0013_compliancetest_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceselector',
            name='region_filter',
            field=models.ManyToManyField(blank=True, related_name='+', to='dcim.region'),
        ),
    ]
