name: Build NetBox nested workflows

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Define .env
      run: >-
        cp development/.env.example development/.env
        && sed -i "s/NETBOX_VERSION=develop/NETBOX_VERSION=${{ inputs.version }}/" development/.env

    - name: docker version
      run: docker version && docker compose version

    - name: Build netbox
      run: cd development && docker compose build
